### ISSUE TITLE
Loading an RDF/XML file into a graph and iterate over statements, get "undefined local variable or method `to_ary'"

### ISSUE THREAD

**Issue by ckristo** [ruby-rdf/rdf#207]
Hi,

is there anything wrong with my (simple) example
````ruby
#!/usr/bin/env ruby

require 'rdf'
require 'rdf/rdfxml'

graph = RDF::Graph.load('foaf.rdf')

puts graph.each do |statement|
  puts statement.to_s
end
````
so that I get the following error?
````
/home/ckristo/.rvm/gems/ruby-2.0.0-p643/gems/rdf-1.1.15/lib/rdf/mixin/enumerable.rb:695:in `method_missing': undefined local variable or method `to_ary' for #<RDF::Queryable::Enumerator:0x007fc8e99d6980> (NameError)
	from rdf_example.rb:8:in `puts'
	from rdf_example.rb:8:in `puts'
	from rdf_example.rb:8:in `<main>'
````

**Comment by ckristo** [comment]
For god's sake, what a stupid mistake *headdesk* ... nevermind (would delete this issue if I could) ::
````ruby
graph.each do |statement| # remove the puts
  puts statement.to_s
end
````

**Comment by bendiken** [comment]
Remove the `puts` in front of `graph.each`, and the example will work.

**Comment by ckristo** [comment]
Thanks .. sorry to bother you with such a stupid question
