### ISSUE TITLE
non-compliant XMLSchema#dateTime format

### ISSUE THREAD

**Issue by jcoyne** [ruby-rdf/rdf#273]
Jena raises this warning when reading graphs generated by RDF.rb
```
WARN 15:35:52.094 (riot) [line: 11, col: 45] Lexical form '2016-02-08T15:35:51.895658027+0000' not valid for datatype http://www.w3.org/2001/XMLSchema#dateTime
```
I suspect it's because the time zone does not have a colin as required by the spec:
https://www.w3.org/TR/xmlschema-2/#dateTime-timezones

```
irb(main):001:0> now = DateTime.now
=> Mon, 08 Feb 2016 09:56:17 -0600
irb(main):002:0> g = RDF::Graph.new
=> #<RDF::Graph:0x3fcdfd180834(default)>
irb(main):003:0> g << RDF::Statement.new(RDF::URI.new, RDF::Vocab::DC.created, now)
=> #<RDF::Graph:0x3fcdfd180834(default)>
irb(main):004:0> g.dump(:ttl)
=> "\n<> <http://purl.org/dc/terms/created> \"2016-02-08T09:56:17.020787-0600\"^^<http://www.w3.org/2001/XMLSchema#dateTime> .\n"
```

**Comment by gkellogg** [comment]
Indeed, the TZ portion must have a ':' in it. However, when I run it, it does. I tried the following:

    now = DateTime.now
    g = RDF::Graph.new
    g << RDF::Statement(RDF::RDFS.Resource, RDF::Vocab::DC.created, now)
    g.dump(:ntriples)

This gives me the following:

    <http://www.w3.org/2000/01/rdf-schema#Resource> <http://purl.org/dc/terms/created> "2016-02-08T13:35:16-08:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> .

Thinking that it might be a Turtle serialization issue, I also serialized with `:ttl`, to get the following:

    <http://www.w3.org/2000/01/rdf-schema#Resource> <http://purl.org/dc/terms/created> "2016-02-08T13:35:16-08:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> .

Literal::DateTime serializes the object form of the literal using `'%Y-%m-%dT%H:%M:%S%:z'`, so Timezone is created using `%:z`. According to [DateTime#strftime](http://ruby-doc.org/stdlib-2.2.4/libdoc/date/rdoc/DateTime.html#method-i-strftime), `%:z` does use a ':' in the string. So, this may be a question of what version of RDF.rb you're using. It looks okay in the latest 1.99 release, but was different in 1.1.x.

You might check again with the develop branch, or 1.99.1. 1.1.17.1 always outputs in UTC. There could also be a Ruby version issue, if DateTime#strftime is implemented differently.

**Comment by jcoyne** [comment]
@gkellogg your example doesn't work for me:

```
now = DateTime.now
g = RDF::Graph.new
g << RDF::Statement(RDF::RDFS.Resource, RDF::Vocab::DC.created, now)
g.dump(:ntriples)
RDF::WriterError: Statement #<RDF::Statement:0x3fbfb149d918(<http://www.w3.org/2000/01/rdf-schema#Resource> <http://purl.org/dc/terms/created> "2016-02-09T11:47:46.106954-0600"^^<http://www.w3.org/2001/XMLSchema#dateTime> .)> is invalid
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rdf-1.99.1/lib/rdf/writer.rb:388:in `write_statement'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rdf-1.99.1/lib/rdf/util/aliasing.rb:46:in `block in alias_method'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rdf-1.99.1/lib/rdf/mixin/writable.rb:34:in `<<'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rdf-1.99.1/lib/rdf/writer.rb:132:in `block (2 levels) in dump'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rdf-1.99.1/lib/rdf/repository.rb:390:in `call'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rdf-1.99.1/lib/rdf/repository.rb:390:in `block (4 levels) in query_pattern'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rdf-1.99.1/lib/rdf/repository.rb:388:in `each'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rdf-1.99.1/lib/rdf/repository.rb:388:in `block (3 levels) in query_pattern'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rdf-1.99.1/lib/rdf/repository.rb:386:in `each'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rdf-1.99.1/lib/rdf/repository.rb:386:in `block (2 levels) in query_pattern'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rdf-1.99.1/lib/rdf/repository.rb:378:in `each'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rdf-1.99.1/lib/rdf/repository.rb:378:in `block in query_pattern'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rdf-1.99.1/lib/rdf/repository.rb:369:in `each'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rdf-1.99.1/lib/rdf/repository.rb:369:in `query_pattern'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rdf-1.99.1/lib/rdf/mixin/queryable.rb:86:in `query'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rdf-1.99.1/lib/rdf/model/graph.rb:262:in `each'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rdf-1.99.1/lib/rdf/mixin/enumerable.rb:159:in `each_statement'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rdf-1.99.1/lib/rdf/writer.rb:131:in `block in dump'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rdf-1.99.1/lib/rdf/writer.rb:153:in `call'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rdf-1.99.1/lib/rdf/writer.rb:153:in `block (2 levels) in buffer'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rdf-1.99.1/lib/rdf/writer.rb:220:in `call'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rdf-1.99.1/lib/rdf/writer.rb:220:in `initialize'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rdf-1.99.1/lib/rdf/ntriples/writer.rb:191:in `initialize'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rdf-1.99.1/lib/rdf/writer.rb:153:in `new'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rdf-1.99.1/lib/rdf/writer.rb:153:in `block in buffer'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rdf-1.99.1/lib/rdf/writer.rb:151:in `open'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rdf-1.99.1/lib/rdf/writer.rb:151:in `buffer'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rdf-1.99.1/lib/rdf/writer.rb:130:in `dump'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rdf-1.99.1/lib/rdf/mixin/enumerable.rb:709:in `dump'
```

**Comment by jcoyne** [comment]
It seems like `require 'active_support'` is doing something funny here.  The failure only occurs when I add `require 'active_support'` prior to `g.dump(:ntriples)`

**Comment by jcoyne** [comment]
Maybe this is the problem?

```
RDF::Literal::DateTime.new(DateTime.now).valid?
#=> false
```

**Comment by no-reply** [comment]
Seems like RDF::Literal is correct to view the date as invalid. 

ActiveSupport documentation uses `+0000` formatting in all of its examples: http://api.rubyonrails.org/classes/DateTime.html

**Comment by jcoyne** [comment]
That is valid for iso8601 but not for xmlschema

**Comment by no-reply** [comment]
Is it correct that it overrides `#strftime` format for `%:z`?

http://apidock.com/ruby/DateTime/strftime
https://github.com/ruby-rdf/rdf/blob/develop/lib/rdf/model/literal/datetime.rb#L10

**Comment by jcoyne** [comment]
This was because I was monkeypatching RDF::Literal::Datetime to get around the precision issue: https://github.com/projecthydra/active_fedora/issues/497
