### ISSUE TITLE
Initial path segments with colon characters confound appending methods

### ISSUE THREAD

**Issue by barmintor** [ruby-rdf/rdf#371]
This is more documentation than bug:

The argument to `RDF::URI#/` and `RDF::URI#join` is a relative path, not a segment. This is especially important if passed a path segment with a colon character (the RDF::URI behavior aligns with RFC 3986 3.3):

```
2.4.1 :006 > base = RDF::URI.new("http://base.info")
 => #<RDF::URI:0x3fea700d8050 URI:http://base.info> 
2.4.1 :007 > base / "rdfs:member"
ArgumentError: Non-absolute URI or string required, got rdfs:member
	from /Users/ba2213/.rvm/gems/ruby-2.4.1/gems/rdf-1.99.1/lib/rdf/model/uri.rb:489:in '/'
	from (irb):7
	from /Users/ba2213/.rvm/gems/ruby-2.4.1/gems/railties-4.2.10/lib/rails/commands/console.rb:110:in 'start'
	from /Users/ba2213/.rvm/gems/ruby-2.4.1/gems/railties-4.2.10/lib/rails/commands/console.rb:9:in 'start'
	from /Users/ba2213/.rvm/gems/ruby-2.4.1/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:68:in 'console'
	from /Users/ba2213/.rvm/gems/ruby-2.4.1/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in 'run_command!'
	from /Users/ba2213/.rvm/gems/ruby-2.4.1/gems/railties-4.2.10/lib/rails/commands.rb:17:in '<top (required)>'
	from bin/rails:4:in 'require'
	from bin/rails:4:in '<main>'
2.4.1 :008 > base.join("rdfs:member")
 => #<RDF::URI:0x3fea700e09f8 URI:rdfs:member> 
2.4.1 :009 > base.join("rdfs:member").to_s
 => "rdfs:member" 
2.4.1 :010 > (base + "rdfs:member").to_s
 => "http://base.infordfs:member" 
2.4.1 :011 > base.join("/rdfs:member").to_s
 => "http://base.info/rdfs:member" 
2.4.1 :012 > base / "/rdfs:member"
 => #<RDF::URI:0x3fea6f5246f0 URI:http://base.info/rdfs:member> 
2.4.1 :013 > base / "./rdfs:member"
 => #<RDF::URI:0x3fea700ec9ec URI:http://base.info/./rdfs:member> 
2.4.1 :014 > base.join("./rdfs:member").to_s
 => "http://base.info/rdfs:member"

```

Best practice for path segments that may contain colons appears to be prepending `./` and using `#join`, which resolves the dot-segments.

**Comment by gkellogg** [comment]
Is there some new descriptive test you'd like to see for `URI#join`, `URI#+` and/or `URI#/`?

The argument(s) may also be an absolute URI, so that RDF::URI('http://example.org/").join("http://example.com") will yield "http://example.com", which is the intent.

We could simply add more examples.

Please consider making a PR.

**Comment by barmintor** [comment]
@gkellogg sure thing (I have to get a local library working first, but should have time to soon)
