### ISSUE TITLE
new error when updating from 2.2.0 to 3.0

### ISSUE THREAD

**Issue by jeffreycwitt** [ruby-rdf/rdf#386]
Hi there, 

I'm getting a strange error when trying to update from 2.2.0 to 3.0. I wonder if you can help me solve it.
I've pasted the error below

@gkellogg I'm updating to 3.0 because I'm trying to integrate the new PR, https://github.com/ruby-rdf/sparql-client/pull/87, which requires rdf 3.0. 

```
/Users/jcwitt/.rvm/gems/ruby-2.2.2/gems/rdf-3.0.4/lib/rdf.rb:185:in `Vocabulary': /Users/jcwitt/.rvm/gems/ruby-2.2.2/gems/rdf-3.0.4/lib/rdf/vocabulary.rb:537: syntax error, unexpected keyword_do_cond, expecting ':' (SyntaxError)
            attributes[ak] = avs.is_a?(Array) ? avs.map do |av|
                                                          ^
/Users/jcwitt/.rvm/gems/ruby-2.2.2/gems/rdf-3.0.4/lib/rdf/vocabulary.rb:540: syntax error, unexpected keyword_do_cond, expecting keyword_end
                RDF::List.new(subject: av) do |nl|
                                             ^
/Users/jcwitt/.rvm/gems/ruby-2.2.2/gems/rdf-3.0.4/lib/rdf/vocabulary.rb:541: syntax error, unexpected keyword_do_cond, expecting keyword_end
                  l.each do |lv|
                           ^
/Users/jcwitt/.rvm/gems/ruby-2.2.2/gems/rdf-3.0.4/lib/rdf/vocabulary.rb:545: syntax error, unexpected keyword_elsif, expecting keyword_end
              elsif av.is_a?(RDF::Node)
                   ^
/Users/jcwitt/.rvm/gems/ruby-2.2.2/gems/rdf-3.0.4/lib/rdf/vocabulary.rb:547: syntax error, unexpected keyword_else, expecting keyword_end
/Users/jcwitt/.rvm/gems/ruby-2.2.2/gems/rdf-3.0.4/lib/rdf/vocabulary.rb:550: syntax error, unexpected ':'
            end.compact : avs
                         ^
/Users/jcwitt/.rvm/gems/ruby-2.2.2/gems/rdf-3.0.4/lib/rdf/vocabulary.rb:618: syntax error, unexpected keyword_end, expecting end-of-input
	from /Users/jcwitt/.rvm/gems/ruby-2.2.2/gems/rdf-rdfxml-2.2.1/lib/rdf/rdfxml/vocab.rb:2:in `<module:RDF>'
	from /Users/jcwitt/.rvm/gems/ruby-2.2.2/gems/rdf-rdfxml-2.2.1/lib/rdf/rdfxml/vocab.rb:1:in `<top (required)>'
	from /Users/jcwitt/.rvm/gems/ruby-2.2.2/gems/rdf-rdfxml-2.2.1/lib/rdf/rdfxml.rb:24:in `require'
	from /Users/jcwitt/.rvm/gems/ruby-2.2.2/gems/rdf-rdfxml-2.2.1/lib/rdf/rdfxml.rb:24:in `<module:RDFXML>'
	from /Users/jcwitt/.rvm/gems/ruby-2.2.2/gems/rdf-rdfxml-2.2.1/lib/rdf/rdfxml.rb:22:in `<module:RDF>'
	from /Users/jcwitt/.rvm/gems/ruby-2.2.2/gems/rdf-rdfxml-2.2.1/lib/rdf/rdfxml.rb:4:in `<top (required)>'
	from /Users/jcwitt/Projects/lombardpress/lbp.rb/lib/lbp/resource.rb:3:in `require'
	from /Users/jcwitt/Projects/lombardpress/lbp.rb/lib/lbp/resource.rb:3:in `<top (required)>'
	from /Users/jcwitt/Projects/lombardpress/lbp.rb/lib/lbp.rb:11:in `require'
	from /Users/jcwitt/Projects/lombardpress/lbp.rb/lib/lbp.rb:11:in `<top (required)>'
	from /Users/jcwitt/Projects/lombardpress/lbp.rb/spec/article_spec.rb:2:in `require'
	from /Users/jcwitt/Projects/lombardpress/lbp.rb/spec/article_spec.rb:2:in `<top (required)>'
	from /Users/jcwitt/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `load'
	from /Users/jcwitt/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `block in load_spec_files'
	from /Users/jcwitt/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `each'
	from /Users/jcwitt/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `load_spec_files'
	from /Users/jcwitt/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:97:in `setup'
	from /Users/jcwitt/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:85:in `run'
	from /Users/jcwitt/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:70:in `run'
	from /Users/jcwitt/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:38:in `invoke'
	from /Users/jcwitt/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/exe/rspec:4:in `<top (required)>'
	from /Users/jcwitt/.rvm/gems/ruby-2.2.2/bin/rspec:23:in `load'
	from /Users/jcwitt/.rvm/gems/ruby-2.2.2/bin/rspec:23:in `<main>'
	from /Users/jcwitt/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jcwitt/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by gkellogg** [comment]
What version of ruby are you running? On what platform.

It thinks there’s a syntax error in the RDF library, which could be an issue with new syntax, but the CI tests for everything back to Ruby 2.2.

**Comment by jeffreycwitt** [comment]
@gkellogg I'm running ruby 2.2.2 on mac

**Comment by gkellogg** [comment]
@jeffreycwitt I can't reproduce your problem. It seems to think that vocabulary.rb in the rdf gem has a syntax error, but all tests pass for 2.2 upwards. The [Travis test on master](https://travis-ci.org/ruby-rdf/rdf/jobs/431133476#L444) (from which 3.0.4 was released) runs ruby 2.2.7. I use rvm on my Mac, and it has 2.2.10 installed. They all run the test without fail, but you seem to fail with a syntax error in vocabulary.rb, which doesn't make sense. It's conceivable that your gem install was corrupted, and that's why the you're getting an error reported, but the line number makes it seems like that version of Ruby doesn't recognize the syntactic construction, which 2.2 certainly does.

It would be great if you can provide me with a minimal script which reproduces the error. You might also try with a newer version of Ruby (although that shouldn't matter); I run 2.5.1 regularly.

**Comment by gkellogg** [comment]
Wait, I did reproduce it on 2.2.2; it seems that they made some changes between 2.2.2 and 2.2.7 which messed "fixed" a parsing problem. I know the gem advertises that it's compatible with versions 2.2.2 and up, but obviously, it's not. I'll see if I can improve that compatibility, but you should probably run on a newer version anyway, to get the benefit of important bug fixes including security patches.

**Comment by gkellogg** [comment]
The code in vocabulary.rb was the only code affected; I've created PR #387 to address this. Let me know if that solves your issues, but I do encourage you to use a newer version of Ruby regardless.

**Comment by gkellogg** [comment]
@jeffreycwitt I went ahead and integrated this, and will release a gem update. I'll hold off on the sparql-client merge until you've had a chance to verify.

**Comment by jeffreycwitt** [comment]
I know you already closed this. But just to confirm, this patch definitely resolved the rdf syntax problem. Thanks.
